### PR TITLE
About us block

### PR DESCRIPTION
**Pull request by veronikaiav**
Added about us block, about us item and block-container

### CODE REVIEW

**Comment by SlinkoMikhail** [comment]
Hello @veronikaiav .
I've done a review of your code. Left a few TODOs, please fix them.

**Comment by veronikaiav** [comment]
@SlinkoMikhail, hi! I've fixed TODOs and added a basic container. Could you check it, please?

**Comment by SlinkoMikhail** [comment]
Hi @veronikaiav .
I left small TODOs for you. Please fix it ASAP.

**Comment by veronikaiav** [comment]
Hello, @SlinkoMikhail! I've fixed TODOs. Could you check it, please?

**Comment by SlinkoMikhail** [comment]
@veronikaiav thank you!
All changes look good. Feel free to merge!

**Pull request merged**
